---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: mbsync-molecule-debian-stretch
    box: debian/jessie64
  - name: mbsync-molecule-debian-buster
    box: debian/buster64
  - name: mbsync-molecule-ubuntu-foster
    box: generic/ubuntu2004
  - name: mbsync-molecule-ubuntu-bionic
    box: generic/ubuntu1804
  - name: mbsync-molecule-centos-7
    box: centos/7
  - name: mbsync-molecule-centos-8
    box: centos/8
provisioner:
  name: ansible
verifier:
  name: ansible
